name: Question Generator Cron Job

on:
    schedule:
        # Runs 4 times daily
        - cron: "0 */6 * * *"
    # Allows manual triggering from the GitHub Actions tab
    workflow_dispatch:

jobs:
    generate-questions:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository code
            - name: Checkout repository
              uses: actions/checkout@v4

            # Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x" # Specify Python 3.x (e.g., '3.11' for a specific version)

            # Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install google-generativeai requests python-dotenv colorlog

            # Run the question generator script
            - name: Run question generator
              env:
                  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
              run: |
                  python3 ./question_generator_custom.py \
                    --api-key "$GEMINI_API_KEY" \
                    --num-questions 75 \
                    --question-types "['MCQ', 'MOC','TRUE_FALSE']" \
                    --difficulty '[1, 2, 3]' \
                    --db-endpoint "https://app.examshala.in/api/create-multiple-questions-in-bank"
